export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN= 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS= 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR= 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN= 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS= 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR= 'LOGIN_USER_ERROR'

export const LOGOUT_USER= 'LOGOUT_USER'

export const CREATE_RESERVATION_BEGIN = 'CREATE_RESERVATION_BEGIN'
export const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS'
export const CREATE_RESERVATION_ERROR = 'CREATE_RESERVATION_ERROR'

export const DELETE_RESERVATION_BEGIN = 'DELETE_RESERVATION_BEGIN'
export const DELETE_RESERVATION_SUCCESS = 'DELETE_RESERVATION_SUCCESS'
export const DELETE_RESERVATION_ERROR = 'DELETE_RESERVATION_ERROR'